/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chris_jangguLang_FileManager */

#ifndef _Included_org_chris_jangguLang_FileManager
#define _Included_org_chris_jangguLang_FileManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chris_jangguLang_FileManager
 * Method:    selectFile
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_chris_jangguLang_FileManager_selectFile
  (JNIEnv *, jobject);

/*
 * Class:     org_chris_jangguLang_FileManager
 * Method:    saveFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_chris_jangguLang_FileManager_saveFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
